// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fylrytiilgkjhqlyetde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5bHJ5dGlpbGdramhxbHlldGRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MDA1NzgsImV4cCI6MjA3Mjk3NjU3OH0.9mc3T-O4ly5Ef0rPOnUm5Ncsq0fIaNYSLlIjgtIEx_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});